name: Simple Test Pipeline

on:
  push:
    branches: [ main ]

jobs:
  quick-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run quick test
        run: |
          echo "Running quick test..."
          node test.js
